// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Token struct {
	ID         int64
	Email      string
	Token      string
	Expiration time.Time
}

type User struct {
	ID       int64
	Email    string
	Verified bool
}

type Video struct {
	ID            int64
	UserEmail     string
	Title         string
	Description   sql.NullString
	FilePath      string
	ThumbnailPath sql.NullString
	Price         float64
	TotalViews    int64
	CreatedAt     sql.NullTime
}
