// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, email string) (int64, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteExpiredTokens(ctx context.Context, expiration time.Time) error
	DeleteToken(ctx context.Context, token string) error
	DeleteVideo(ctx context.Context, externalID string) error
	GetToken(ctx context.Context, token string) (Token, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetVideo(ctx context.Context, externalID string) (Video, error)
	IncrementVideoViews(ctx context.Context, externalID string) (Video, error)
	ListUserVideos(ctx context.Context, userEmail string) ([]Video, error)
	SearchVideos(ctx context.Context, arg SearchVideosParams) ([]Video, error)
	UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error
	VerifyToken(ctx context.Context, arg VerifyTokenParams) (string, error)
}

var _ Querier = (*Queries)(nil)
